version: '3.8'
name: "chat_app_docker"
services:
  postgres:
    image: postgres:15
    container_name: postgres_chat_app
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chat-network

  redis:
    image: redis:latest
    container_name: redis_chat_app
    ports:
      - "6378:6379"
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  postgres-data:
