spring:
  application:
    name: chat-application

  datasource:
    url: jdbc:postgresql://${SERVICE_DATASOURCE_HOST:localhost:5432}/chat_db?schema=public
    username: chat_user
    password: chat_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
        generate_statistics: false
        type: trace
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 1000

chat:
  threadpool:
    core-size: 10
    max-size: 50
    queue-capacity: 100
    keep-alive-seconds: 60

websocket:
  endpoint: /ws
  allowed-origins: "*"
